/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "md:flex",
    "md:hidden",
    "md:block",
    "md:grid",
    "md:grid-cols-2",
    "md:grid-cols-3",
    "md:grid-cols-4",
    "sm:flex",
    "sm:hidden",
    "sm:block",
    "sm:grid",
    "sm:grid-cols-2",
    "sm:grid-cols-3",
    "sm:w-auto",
    "sm:flex-row",
    "sm:text-5xl",
    "sm:text-6xl",
    "sm:text-4xl",
    "sm:text-3xl",
    "sm:text-xl",
    "sm:text-lg",
    "sm:grid-cols-2",
    "sm:grid-cols-3",
    "sm:grid-cols-4",
    "lg:grid-cols-2",
    "lg:grid-cols-3",
    "lg:grid-cols-4",
    "lg:block",
    "lg:flex",
    "lg:hidden",
    "lg:text-7xl",
    "lg:text-5xl",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#3B5BDB",
          50: "#EBF0FE",
          100: "#D6E1FC",
          200: "#AEC3F9",
          300: "#85A5F6",
          400: "#5D87F3",
          500: "#3B5BDB",
          600: "#2F48B0",
          700: "#233585",
          800: "#18225A",
          900: "#0C112F",
        },
        navy: {
          DEFAULT: "#0f1f3d",
          900: "#0f1f3d",
          800: "#1a2640",
          700: "#2a3b66",
          600: "#3a508c",
          500: "#5570b2",
          400: "#778dc1",
          300: "#99aad1",
          200: "#bbc6e0",
          100: "#dde3f0",
          50: "#eef1f8",
        },
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        sans: ["DM Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
